language: objective-c
osx_image: xcode7.3
before_install:
  - brew update
  - brew upgrade python
  - nvm install v8.7.0
  - brew install opam
  - opam init -y
  - opam switch create "$OCAML_VERSION"
  - eval `opam config env`
  - opam update
before_script:
  - opam install -y utop
  - opam pin add -y reason .
  - opam pin add -y rtop .
script:
  - make test-ci
  - git diff --exit-code
env:
  - OCAML_VERSION=4.02.3
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.07.0
notifications:
  email:
    - chenglou@fb.com
    - jordanjcw@fb.com
